name: Build mpc-os image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-sks-hello:
    name: Build mpc-os image
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: >
          sudo apt-get install
          coreutils quilt parted qemu-user-static debootstrap zerofree zip
          dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc
          qemu-utils kpartx

      - name: Build image
        run: sudo ./build.sh

      - name: Release image
        uses: softprops/action-gh-release@v1

        with:
          draft: false
          prerelease: false
          files: ./deploy/*.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
